baseURL = "https://litvinenko.info/"
languageCode = "en-us"
title = "Alex Litvinenko"

theme = "hyde-hyde"
#DisqusShortname = "aazon"

[params]
  themeColor = "theme-base-0b"
  highlightjs = true
  highlightjsstyle = "github"
  author = "Alex Litvinenko"
  description = "Notes on my daily DevOps tasks"
#  showBuiltWith = true
  postNavigation = false
  sidebarSticky = true
#  layoutReverse = true

[params.social]
  linkedin = "aazon"
  github = "aazon"
#  twitter = "aazon"
  telegram = "aazon"
  gravatar = "litvinenkoalex@gmail.com"

## Main Menu
#[[menu.main]]
#    name = "Posts"
#    weight = 100
#    identifier = "posts"
#    url = "/posts/"
#[[menu.main]]
#    name = "About"
#    identifier = "about"
#    weight = 300
#    url = "/about/"
