baseURL: 'https://litvinenko.tech'
title: Alex on DevOps
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true
params:
  author: Alex Litvinenko
  description: Alex Litvinenko personal website
  keywords: 'blog,developer,personal'
  info:
  - Cloud Architect
  - DevOps Engineer
  avatarURL: images/avatar.jpg
  gravatar: litvinenkoalex@gmail.com
  dateFormat: 'January 2, 2006'
  since: 2017
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: [ ]
  customSCSS: [ ]
  customJS: [ ]
  social:
  - name: GitHub
    icon: fa fa-2x fa-github
    weight: 2
    url: 'https://github.com/aazon/'
  - name: GitLab
    icon: fa fa-2x fa-gitlab
    weight: 2
    url: 'https://gitlab.com/johndoe/'
  #  - name: Twitter
  #    icon: fa fa-2x fa-twitter
  #    weight: 3
  #    url: 'https://twitter.com/aazon/'
  - name: LinkedIn
    icon: fa fa-2x fa-linkedin
    weight: 1
    url: 'https://www.linkedin.com/in/aazon/'
  - name: Telegram
    icon: fa fa-2x fa-telegram
    weight: 4
    url: https://t.me/aazon
#  - name: Medium
#    icon: fa fa-2x fa-medium
#    weight: 5
#    url: 'https://medium.com/@johndoe'
#  - name: RSS
#    icon: fa fa-2x fa-rss
#    weight: 6
#    url: 'https://myhugosite.com/index.xml'
#    rel: alternate
#    type: application/rss+xml
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
      - name: About
        weight: 1
        url: about/
      - name: Blog
        weight: 2
        url: posts/
      - name: Projects
        weight: 3
        url: projects/
      - name: Contact me
        weight: 5
        url: contact/
  de:
    languageName: ':de:'
    title: Alex über DevOps
    params:
      author: Alex Litvinenko
      info:
      - Cloud Architekt
      - DevOps Ingenieur
      description: Persönliche Website von Alex Litvinenko
      keywords: 'blog,pessoal'
    menu:
      main:
      - name: Über mich
        weight: 1
        url: about/
      - name: Blog
        weight: 2
        url: posts/
      - name: Projekte
        weight: 3
        url: projects/
      - name: Kontakt
        weight: 5
        url: contact/
