baseURL: 'https://litvinenko.tech'
title: Alex Litvinenko
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true
params:
  author: Alex Litvinenko
  description: Alex Litvinenko personal website
  keywords: 'blog,developer,personal'
  info:
  - Cloud Architect
  - DevOps Engineer
  avatarURL: images/avatar.jpg
  gravatar: litvinenkoalex@gmail.com
  dateFormat: 'January 2, 2006'
  since: 2017
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: [ ]
  customSCSS: [ ]
  customJS: [ ]
  social:
  - name: Email
    icon: fa fa-2x fa-envelope
    weight: 1
    url: 'mailto:hello@litvinenko.tech'
  - name: LinkedIn
    icon: fa fa-2x fa-linkedin
    weight: 1
    url: 'https://www.linkedin.com/in/aazon/'
  - name: GitHub
    icon: fa fa-2x fa-github-alt
    weight: 2
    url: 'https://github.com/aazon/'
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
      - name: About
        weight: 1
        url: about/
#      - name: Services
#        weight: 2
#        url: services/
#      - name: Projects
#        weight: 3
#        url: projects/
      - name: Blog
        weight: 4
        url: blog/
      - name: Contact
        weight: 5
        url: contact/
#  de:
#    languageName: ':de:'
#    title: Alex über DevOps
#    params:
#      author: Alex Litvinenko
#      info:
#      - Cloud Architekt
#      - DevOps Ingenieur
#      description: Persönliche Website von Alex Litvinenko
#      keywords: 'blog'
#    menu:
#      main:
#      - name: Über mich
#        weight: 1
#        url: about/
#      - name: Projekte
#        weight: 3
#        url: projects/
#      - name: Kontakt
#        weight: 5
#        url: contact/
markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
