baseURL: 'https://litvinenko.tech'
defaultContentLanguage: en
enableEmoji: true
languageCode: en
paginate: 20
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: bw
pygmentsUseClasses: false
pygmentsUseClassic: false
theme: hugo-coder
title: Alex Litvinenko

params:
  author: Alex Litvinenko
  avatarURL: /alex_litvinenko.jpg
  colorScheme: light
  customCSS:
    - "css/styles.css"
  customJS: []
  customSCSS: []
  dateFormat: 'January 2, 2006'
  description: Alex Litvinenko personal website
  favicon_16: "/icons/favicon-16x16.png"
  favicon_32: "/icons/favicon-32x32.png"
  hideColorSchemeToggle: true
  info:
    - Cloud Architect
    - DevOps Engineer
  keywords: 'blog,developer,personal'
  manifest: "site.webmanifest"
  maxSeeAlsoItems: 5
  rtl: false
  since: 2017
  social:
    - name: Email
      icon: fa fa-2x fa-envelope
      weight: 1
      url: 'mailto:hello@litvinenko.tech'
    - name: LinkedIn
      icon: fa fa-2x fa-linkedin
      weight: 1
      url: 'https://www.linkedin.com/in/aazon/'
    - name: GitHub
      icon: fa fa-2x fa-github-alt
      weight: 2
      url: 'https://github.com/aazon/'
  touchicon: "/icons/apple-touch-icon.png"

taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          weight: 1
          url: about/
        #      - name: Services
        #        weight: 2
        #        url: services/
        #      - name: Projects
        #        weight: 3
        #        url: projects/
        - name: Blog
          weight: 4
          url: blog/
        - name: Contact
          weight: 5
          url: contact/
#  de:
#    languageName: ':de:'
#    title: Alex über DevOps
#    params:
#      author: Alex Litvinenko
#      info:
#      - Cloud Architekt
#      - DevOps Ingenieur
#      description: Persönliche Website von Alex Litvinenko
#      keywords: 'blog'
#    menu:
#      main:
#      - name: Über mich
#        weight: 1
#        url: about/
#      - name: Projekte
#        weight: 3
#        url: projects/
#      - name: Kontakt
#        weight: 5
#        url: contact/
markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: nord
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
