on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.111.0'
        extended: true
    - name: Build
      run: hugo --minify --source=website
    - name: Publish
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: aazon # e.g. 'my-project'
        directory: website/public # e.g. 'dist'
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
